server:
  # 端口设置
  port: 8001
  # 根路径设置
  servlet:
    context-path: /springboot-demo

# 注入单一属性
user: "liuShuTong"
age: 23
birthday: 1996-01-29 18:23:34
content: "userName is : ${user},Age is : ${age}, birthday is ${birthday}"

# 注入类型属性
network:
  host: http://www.baidu.com
  port: 8443

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/sell?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
